name: Unit test

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cargo Build
        run: cargo build

      - name: Cargo Test
        run: cargo test
