name: Unit test

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install tesseract leptonica
      - run: |
          cargo test
          cargo build --release
